bsexec .. /sbin/mount -u -o rw,suid,dev /
setenv DYLD_INSERT_LIBRARIES /private/var/aquila/amfi_bypass.dylib
unload /System/Library/LaunchDaemons/com.apple.MobileFileIntegrity.plist
load /System/Library/LaunchDaemons/com.apple.MobileFileIntegrity.plist
start com.apple.MobileFileIntegrity
bsexec .. /Library/Logs/CrashReporter/Baseband
unsetenv DYLD_INSERT_LIBRARIES
